pocket_consumer_key = '' # paste the 'consumer key' from your Pocket app between the quotes here
pocket_redirect_uri = 'https://hugh.li/success'
items_per_cycle = 10 # integer
archive_tag = 'tbr' # apply this tag before archiving items. This is case-insensitive and Pocket will always downcase it
ignore_tags = {'ignore'} # don't stash any items with these tags
ignore_faves = True # don't stash items that are favorited
replace_all_tags = False # if set to True this will replace ALL tags on an item in the user's List with the archive_tag and anything in retain_tags. If set to False, the archive tag is still added but any existing tags are retained.
retain_tags = {'glam blog club', 'aus glam blogs', 'empocketer'} # if replace_all_tags is set to True, you can still retain particular tags by adding them to the exclude_tags list. Note that this is a Set, not a List
longreads_wordcount = 3000 # integer - if there are more than this many words, the article will be classified as a 'long read'
num_videos = None # if you change this to an integer this many items_per_cycle will be videos (if there are any videos in your list)
num_images = None # if you change this to an integer this many items_per_cycle will be images (if there are any images in your list)
num_longreads = 2 # if this is an integer this many items_per_cycle will be longreads (if there are any longreads in your list). If all your items are longreads you will still get the total items_per_cycle. Change to None or False if you don't want to filter longreads
